Controllers/CustomerPageController.cs
using System;
using System.Linq;
using CustomerManager2.Data;
using CustomerManager2.Helpers;
using CustomerManager2.Models;
using CustomerManager2.Models.CustomerModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace CustomerManager2.Controllers
{
    [Authorize(Roles = "Customer")]
    public class CustomerPageController : Controller
    {
        private IServiceProvider _serviceProvider;
        private ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        public CustomerPageController(IServiceProvider serviceProvider, ApplicationDbContext context)
        {
            _serviceProvider = serviceProvider;
            _context = context;
            _userManager = serviceProvider.GetRequiredService<UserManager<ApplicationUser>>();
        }

        public IActionResult Index()
        {
            return View();
        }

        #region CONTACT
        public IActionResult CreateContact()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateContact(ContactsDetail contactsDetail)
        {
            if (contactsDetail == null)
            {
                throw new ArgumentNullException(nameof(contactsDetail));
            }

            if (ModelState.IsValid)
            {
                var username = User.Identity.Name;
                contactsDetail.CustomerInformation = _context.CustomerInformations.Where(c => c.Name == username).FirstOrDefault();

                _context.ContactsDetails.Add(contactsDetail);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(contactsDetail);
        }

        public IActionResult EditContact(int? id)
        {
            var contactsDetail = _context.ContactsDetails.Find(id);
            return View(contactsDetail);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditContact(ContactsDetail contactsDetail)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(contactsDetail).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contactsDetail);
        }

        public IActionResult DeleteContact(int? id)
        {
            ContactsDetail contactsDetail = _context.ContactsDetails.Find(id);
            return View(contactsDetail);
        }

        [HttpPost, ActionName("DeleteContact")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteContactConfirmed(int id)
        {
            var contactsDetail = _context.ContactsDetails.Find(id);
            _context.ContactsDetails.Remove(contactsDetail);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        #endregion

        #region DEPARTAMENT
        public IActionResult CreateDepartament()
        {
            var departament = new Departament();

            var username = User.Identity.Name;

            departament.Customer = (from customer in _context.CustomerInformations
                                    where customer.Name == username
                                    select customer).FirstOrDefault();


            var listOfUsers = (from loginUser in _context.LoginUsers
                               where loginUser.Customer.Name == username
                               select loginUser).ToList().Select(u => new SelectListItem
                               {
                                   Text = u.Name,
                                   Value = u.Name
                               });

            ViewBag.ListOfUsers = listOfUsers;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateDepartament(Departament departament)
        {
            if (ModelState.IsValid)
            {
                var username = User.Identity.Name;

                departament.Customer = (from customer in _context.CustomerInformations
                                        where customer.Name == username
                                        select customer).FirstOrDefault();

                departament.Manager = (from users in _context.LoginUsers
                                       where users.Name == departament.ManagerName
                                       select users).FirstOrDefault();

                _context.Departaments.Add(departament);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(departament);
        }

        public IActionResult EditDepartament(int? id)
        {
            Departament departament = _context.Departaments.Find(id);

            var username = User.Identity.Name;

            departament.Customer = (from customer in _context.CustomerInformations
                                    where customer.Name == username
                                    select customer).FirstOrDefault();


            var listOfUsers = (from users in _context.LoginUsers
                               where users.Customer.Name == username
                               select users).ToList().Select(u => new SelectListItem
                               {
                                   Text = u.Name,
                                   Value = u.Name
                               });

            ViewBag.ListOfUsers = listOfUsers;

            return View(departament);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditDepartament(Departament departament)
        {
            if (ModelState.IsValid)
            {
                departament.Manager = (from users in _context.LoginUsers
                                       where users.Name == departament.ManagerName
                                       select users).FirstOrDefault();
                try
                {
                    //I admit that it's not legal
                    var sqlCommand = String.Format("update dbo.Departaments set ManagerId = {0} where Id = {1}", departament.Manager.Id, departament.Id);
                    _context.Database.ExecuteSqlCommand(sqlCommand);
                    _context.Entry(departament).State = EntityState.Modified;
                    _context.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch
                {
                    ModelState.AddModelError("FullName", "Query error");
                    return View(departament);
                }
            }

            return View(departament);
        }
        public IActionResult DeleteDepartament(int? id)
        {
            var departament = _context.Departaments.Find(id);
            return View(departament);
        }

        [HttpPost, ActionName("DeleteDepartament")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteDepartamentConfirmed(int id)
        {
            var departament = _context.Departaments.Find(id);
            _context.Departaments.Remove(departament);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        #endregion

        #region USERS
        public IActionResult CreateUser()
        {
            var loginUser = new LoginUser();

            var username = User.Identity.Name;

            loginUser.Customer = (from customer in _context.CustomerInformations
                                  where customer.Name == username
                                  select customer).FirstOrDefault();


            var listOfDepartamets = (from departament in _context.Departaments
                                     where departament.Customer.Name == username
                                     select departament).ToList().Select(u => new SelectListItem
                                     {
                                         Text = u.Name,
                                         Value = u.Name
                                     });

            ViewBag.ListOfDepartaments = listOfDepartamets;
            return View(loginUser);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateUser(LoginUser loginUser)
        {
            var username = User.Identity.Name;

            if (ModelState.IsValid)
            {
                try
                {

                    UserActionsHelper.CreateUser(_serviceProvider, _context, loginUser.UserName, loginUser.Mail, loginUser.Password, "User");
                    loginUser.OldName = loginUser.UserName;

                    loginUser.Customer = (from customer in _context.CustomerInformations
                                          where customer.Name == username
                                          select customer).FirstOrDefault();

                    loginUser.Departament = (from departament in _context.Departaments
                                             where departament.Name == loginUser.DepartamentName
                                             select departament).FirstOrDefault();

                    loginUser.Id = _context.LoginUsers.LastOrDefault() != null ? _context.LoginUsers.AsNoTracking().LastOrDefault().Id + 1 : 1;

                    _context.LoginUsers.Add(loginUser);
                    _context.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch
                {
                    ModelState.AddModelError("FullName", "Query error");
                    return View(loginUser);
                }
            }

ViewComponents/ContactsDetailViewComponent.cs
using CustomerManager2.Data;
using CustomerManager2.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Linq;

namespace CustomerManager2.ViewComponents
{
    public class ContactsDetailViewComponent: ViewComponent
    {
        private IServiceProvider _serviceProvider;
        private ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        public ContactsDetailViewComponent(IServiceProvider serviceProvider, ApplicationDbContext context)
        {
            _serviceProvider = serviceProvider;
            _context = context;
            _userManager = serviceProvider.GetRequiredService<UserManager<ApplicationUser>>();
        }

        public IViewComponentResult Invoke()
        {
            var username = User.Identity.Name;
            var contactsToCustomer = _context.ContactsDetails.Where(c => c.CustomerInformation.Name == username).Include(c => c.CustomerInformation).ToList();
            return View(contactsToCustomer);
        }
    }
}

ViewComponents/DepartamentViewComponent.cs
using CustomerManager2.Data;
using CustomerManager2.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Linq;

namespace CustomerManager2.ViewComponents
{
    public class DepartamentViewComponent : ViewComponent
    {
        private IServiceProvider _serviceProvider;
        private ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        public DepartamentViewComponent(IServiceProvider serviceProvider, ApplicationDbContext context)
        {
            _serviceProvider = serviceProvider;
            _context = context;
            _userManager = serviceProvider.GetRequiredService<UserManager<ApplicationUser>>();
        }

        public IViewComponentResult Invoke()
        {
            var username = User.Identity.Name;
            var departamentsToCustomer = _context.Departaments.Where(c => c.Customer.Name == username).Include(c => c.Customer).Include(c => c.UsersInDepartament).ToList();
            return View(departamentsToCustomer);
        }
    }
}

ViewComponents/LoginUserViewComponent.cs
using CustomerManager2.Data;
using CustomerManager2.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Linq;

namespace CustomerManager2.ViewComponents
{
    public class LoginUserViewComponent : ViewComponent
    {
        private IServiceProvider _serviceProvider;
        private ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        public LoginUserViewComponent(IServiceProvider serviceProvider, ApplicationDbContext context)
        {
            _serviceProvider = serviceProvider;
            _context = context;
            _userManager = serviceProvider.GetRequiredService<UserManager<ApplicationUser>>();
        }

        public IViewComponentResult Invoke()
        {
            var username = User.Identity.Name;
            var loginUsersToCustomer = _context.LoginUsers.Where(c => c.Customer.Name == username).Include(c => c.Customer).Include(c => c.DepartamentsToManage).ToList();
            return View(loginUsersToCustomer);
        }
    }
}

Views/CustomerPage/CreateContact.cshtml
@model CustomerManager2.Models.CustomerModels.ContactsDetail

@{
    ViewData["Title"] = "CreateContact";
}

<h2>CreateContact</h2>

<h4>ContactsDetail</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateContact">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<input type="hidden" asp-for="Id" />*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <input asp-for="Role" class="form-control" />
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mail" class="control-label"></label>
                <input asp-for="Mail" class="form-control" />
                <span asp-validation-for="Mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/CustomerPage/CreateDepartament.cshtml
@model CustomerManager2.Models.CustomerModels.Departament

@{
    ViewData["Title"] = "CreateDepartament";
}

<h2>CreateDepartament</h2>

<h4>Departament</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateDepartament">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<input type="hidden" asp-for="Id" />*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ManagerName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.ManagerName, (IEnumerable<SelectListItem>)ViewBag.ListOfUsers)
                    @Html.ValidationMessageFor(model => model.ManagerName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/CustomerPage/CreateUser.cshtml
@model CustomerManager2.Models.CustomerModels.LoginUser

@{
    ViewData["Title"] = "CreateUser";
}

<h2>CreateUser</h2>

<h4>LoginUser</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateUser">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
            <label asp-for="Id" class="control-label"></label>
            <select asp-for="Id" class="form-control" asp-items="ViewBag.Id"></select>*@
        </div>
            @*<input type="hidden" asp-for="Id" />*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mobile" class="control-label"></label>
                <input asp-for="Mobile" class="form-control" />
                <span asp-validation-for="Mobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mail" class="control-label"></label>
                <input asp-for="Mail" class="form-control" />
                <span asp-validation-for="Mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.DepartamentName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.DepartamentName, (IEnumerable<SelectListItem>)ViewBag.ListOfDepartaments)
                    @Html.ValidationMessageFor(model => model.DepartamentName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/CustomerPage/DeleteContact.cshtml
@model CustomerManager2.Models.CustomerModels.ContactsDetail

@{
    ViewData["Title"] = "DeleteContact";
}

<h2>DeleteContact</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ContactsDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Mail)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Mail)
        </dd>
    </dl>
    
    <form asp-action="DeleteContact">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/CustomerPage/DeleteDepartament.cshtml
@model CustomerManager2.Models.CustomerModels.Departament

@{
    ViewData["Title"] = "DeleteDepartament";
}

<h2>DeleteDepartament</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Departament</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
    
    <form asp-action="DeleteDepartament">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/CustomerPage/DeleteUser.cshtml
@model CustomerManager2.Models.CustomerModels.LoginUser

@{
    ViewData["Title"] = "DeleteUser";
}

<h2>DeleteUser</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LoginUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Mail)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Mail)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Departament)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Departament.Address)
        </dd>
    </dl>
    
    <form asp-action="DeleteUser">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/CustomerPage/EditContact.cshtml
@model CustomerManager2.Models.CustomerModels.ContactsDetail

@{
    ViewData["Title"] = "EditContact";
}

<h2>EditContact</h2>

<h4>ContactsDetail</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditContact">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <input asp-for="Role" class="form-control" />
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mail" class="control-label"></label>
                <input asp-for="Mail" class="form-control" />
                <span asp-validation-for="Mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/CustomerPage/EditDepartament.cshtml
@model CustomerManager2.Models.CustomerModels.Departament

@{
    ViewData["Title"] = "EditDepartament";
}

<h2>EditDepartament</h2>

<h4>Departament</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditDepartament">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ManagerName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.ManagerName, (IEnumerable<SelectListItem>)ViewBag.ListOfUsers)
                    @Html.ValidationMessageFor(model => model.ManagerName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/CustomerPage/EditUser.cshtml
@model CustomerManager2.Models.CustomerModels.LoginUser

@{
    ViewData["Title"] = "EditUser";
}

<h2>EditUser</h2>

<h4>LoginUser</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditUser">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mobile" class="control-label"></label>
                <input asp-for="Mobile" class="form-control" />
                <span asp-validation-for="Mobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mail" class="control-label"></label>
                <input asp-for="Mail" class="form-control" />
                <span asp-validation-for="Mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.DepartamentName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.DepartamentName, (IEnumerable<SelectListItem>
                        )ViewBag.ListOfDepartaments)
                        @Html.ValidationMessageFor(model => model.DepartamentName, "", new { @class = "text-danger" })
                </div>
            </div>
            <input type="hidden" asp-for="Departament.Address" value="SomeValue" />
            <input type="hidden" asp-for="Departament.Name" value="SomeValue" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/CustomerPage/Index.cshtml
@model CustomerManager2.Data.ApplicationDbContext
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<div>
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
            <a href="#first" aria-controls="first" role="tab" data-toggle="tab">Contacts</a>
        </li>
        <li role="presentation">
            <a href="#second" aria-controls="second" role="tab" data-toggle="tab">Departaments</a>
        </li>
        <li role="presentation">
            <a href="#third" aria-controls="second" role="tab" data-toggle="tab">Users</a>
        </li>
    </ul>

    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="first">
            @await Component.InvokeAsync("ContactsDetail")
        </div>
        <div role="tabpanel" class="tab-pane" id="second">
            @await Component.InvokeAsync("Departament")
        </div>
        <div role="tabpanel" class="tab-pane" id="third">
            @await Component.InvokeAsync("LoginUser")
        </div>
    </div>
</div>